[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = ["pip install -r requirements.production.txt"]

[phases.build]
cmds = ["python init_db.py"]

[start]
cmd = "uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
