[phases.setup]
nixPkgs = ["python310", "nodejs-18_x"]

[phases.install]
cmds = ["pip install -r requirements.production.txt", "cd frontend && npm ci"]

[phases.build]
cmds = ["python init_db.py", "cd frontend && npm run build"]

[start]
cmd = "uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
